name: storybook publish stage

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Test CDK code
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'


      - name: Clone Golang app
        uses: actions/checkout@v2
        with:
          repository: dcotelo/golang-example-app
          path: resources/docs/2.x
          ref: 2.x
        
      - name: npm install
        run: |
          npm install


      - name: npm test
        run: |
          npm test

