name: storybook publish stage

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Test CDK code
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@master
        with:
          node-version: '14'
          name: dcotelo/golang-example-app     <-- clone https://github.com/dcotelo/golang-example-app
          ref: refs/heads/release


      - name: npm install
        run: |
          npm install


      - name: npm test
        run: |
          npm test

