name: CDK test

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, closed ]
  push:
      - '!master'
jobs:
  build:
    name: Test CDK code
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
        with:
          node-version: '18'


      - name: Clone Golang app
        uses: actions/checkout@v2
        with:
          repository: dcotelo/golang-example-app
          path: golang-example-app/
          ref: main
        
      - name: ls 
        run: |
          ls -l 
          
      - name: npm install
        run: |
          npm install


      - name: npm test
        run: |
          npm test -- -u

      - name: cdk synth
        run: |
          npm run cdk synth